version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # Corregido aquí
    restart: unless-stopped
    command: go run cmd/main.go -b 0.0.0.
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_ROOT_PASSWORD: admin@admin
      POSTGRES_DB: z0
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pg_data:
